
title: "David Wilcox"
url: "https://davidcwilcoxbuffs.github.io"  
baseurl: ""                     
remote_theme: andrewhwanpark/brutalist-blog

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
